import { JewelryItem } from '../lib/supabase';

export const localJewelryItems: JewelryItem[] = [
    {
        id: '1',
        name: "Diamond Engagement Ring",
        description: "Stunning 1.5 carat diamond ring set in 18k white gold",
        price: 8500.00,
        category: "rings",
        image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'gold',
        weight: 4.5,
        wastage_percent: 12,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '2',
        name: "Gold Tennis Bracelet",
        description: "Elegant 14k gold bracelet with perfect round diamonds",
        price: 4200.00,
        category: "bracelets",
        image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb0ce33e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'gold',
        weight: 8.2,
        wastage_percent: 15,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '3',
        name: "Pearl Necklace",
        description: "Classic strand of genuine South Sea pearls",
        price: 3200.00,
        category: "necklaces",
        image_url: "https://images.unsplash.com/photo-1599643478518-a744c5b7fdf1?auto=format&fit=crop&w=400&q=80",
        metal_type: 'none',
        weight: 0,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '4',
        name: "Sapphire Earrings",
        description: "Royal blue sapphires surrounded by diamonds in 18k gold",
        price: 2800.00,
        category: "earrings",
        image_url: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=400&q=80",
        metal_type: 'gold',
        weight: 5.4,
        wastage_percent: 10,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '5',
        name: "Rose Gold Watch",
        description: "Luxury timepiece with leather strap and mother-of-pearl dial",
        price: 5500.00,
        category: "watches",
        image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80",
        metal_type: 'none',
        weight: 0,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '6',
        name: "Platinum Wedding Band",
        description: "Simple and elegant platinum band for timeless commitment",
        price: 1800.00,
        category: "rings",
        image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'platinum',
        weight: 4.8,
        wastage_percent: 10,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '7',
        name: "Emerald Pendant",
        description: "Vibrant Colombian emerald in diamond halo setting",
        price: 3900.00,
        category: "pendants",
        image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb0ce33e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'gold',
        weight: 3.2,
        wastage_percent: 8,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '8',
        name: "Sterling Silver Chain",
        description: "Elegant sterling silver chain for daily wear",
        price: 1200.00,
        category: "chains",
        image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'silver',
        weight: 12.5,
        wastage_percent: 5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '9',
        name: "24K Gold Coin (1g)",
        description: "Pure 24K gold coin for investment",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=400&q=80",
        metal_type: 'gold',
        weight: 1,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '10',
        name: "24K Gold Coin (2g)",
        description: "Pure 24K gold coin for investment",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=400&q=80",
        metal_type: 'gold',
        weight: 2,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '11',
        name: "24K Gold Coin (3g)",
        description: "Pure 24K gold coin for investment",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=400&q=80",
        metal_type: 'gold',
        weight: 3,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '12',
        name: "Fine Silver Coin (1g)",
        description: "999 Pure Silver Investment Coin",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb0ce33e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'silver',
        weight: 1,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '13',
        name: "Fine Silver Coin (2g)",
        description: "999 Pure Silver Investment Coin",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb0ce33e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'silver',
        weight: 2,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '14',
        name: "Fine Silver Coin (3g)",
        description: "999 Pure Silver Investment Coin",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb0ce33e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'silver',
        weight: 3,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '15',
        name: "Platinum Investment Coin (1g)",
        description: "999 Pure Platinum Bar",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'platinum',
        weight: 1,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '16',
        name: "Platinum Investment Coin (2g)",
        description: "999 Pure Platinum Bar",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'platinum',
        weight: 2,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '17',
        name: "Platinum Investment Coin (3g)",
        description: "999 Pure Platinum Bar",
        price: 0,
        category: "coins",
        image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80",
        metal_type: 'platinum',
        weight: 3,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '18',
        name: "Round Brilliant Diamond (1.0ct)",
        description: "GIA Certified, IF Clarity, Exc Cut",
        price: 0,
        category: "diamonds",
        image_url: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=400&q=80",
        metal_type: 'diamond',
        weight: 1.0,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '19',
        name: "Round Brilliant Diamond (0.5ct)",
        description: "GIA Certified, VVS1 Clarity",
        price: 0,
        category: "diamonds",
        image_url: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=400&q=80",
        metal_type: 'diamond',
        weight: 0.5,
        wastage_percent: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];
